apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cgitask-hpa
  namespace: cgitask
spec:
  maxReplicas: 10
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cgitask-depl
  targetCPUUtilizationPercentage: 50